### ISSUE TITLE
Can't retrieving NXP-NCI NFC delivery

### ISSUE THREAD

**Issue by ryanw0602** [NXPNFCLinux/nxpnfc_android_lollipop#1]
hello 

I follow AN11690.pdf ( Android Lollipop ) 

step 1
Retrieve the NXP-NCI NFC Android manifest file from [NxpNfc_Android_lollipop] using wget command:
$ wget https://raw.githubusercontent.com/NXPNFCLinux/nxpnfc_android_lollipop/master/nxpnfc_manifest.xml

Then install it as local manifest in the AOSP source directory:
& mv nxpnfc_manifest.xml {ANDROID_BUILD_TOP}/.repo/local_manifests/

And apply changes brought by NXP-NCI NFC Android manifest:
$ repo sync --force-sync

**Result:
ryan@ubuntu:~/rk3288/3288$ repo sync --force-sync
error: command 'sync' requires repo to be installed first.
         Use "repo init" to install it here.

ryan@ubuntu:~/rk3288/3288$ repo init
Get https://gerrit.googlesource.com/git-repo/clone.bundle
Get https://gerrit.googlesource.com/git-repo
remote: Finding sources: 100% (11/11)
remote: Total 11 (delta 0), reused 11 (delta 0)
Unpacking objects: 100% (11/11), done.
From https://gerrit.googlesource.com/git-repo
   685320b..1f36570  master     -> origin/master
fatal: manifest url (-u) is required.**

P.S.	 repo is download from:
curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo

how can i retrieving NXP-NCI NFC for Lollipop? thanks

**Comment by jgeslin** [comment]
Hi,

The AN11690 provides guidelines to add PN71xx support to Android based device. The process is done starting from the AOSP source code, adapted to the targeted MPU.
So the repo init must be relates to your target. For instance, if you wish to add PN71xx support on HiKey960 board (one of the android reference board) you must first follow guidelines for building AOSP for this board (see https://source.android.com/setup/devices) before following AN11690 guidelines.
Or for Raspberry Pi3: https://github.com/tab-pi/platform_manifest.

What's your targeted board ?

Regards,
Jeremy.

**Comment by ryanw0602** [comment]
hi Jeremy,

Thanks for your reply. My board chip is RK3288, the AOSP is provided from manufacturer.
Can I download the PN71xx support file from another way and repleace it manually?

Regards,
Ryan

**Comment by jgeslin** [comment]
Hi,

You must start from the AOSP environment set up for your board. Then add the PN71xx manifest file as detailed in step 1.
Indeed the only way to add PN71xx support is to both add the pn5xx-i2c driver to the board kernel and to rebuild the Android image with PN71xx patches.

Regards,
Jeremy.

**Comment by ryanw0602** [comment]
hi,

I setup the AOSP environment but i can't find the folder "local_manifests" under ".repo" 
{ANDROID_BUILD_TOP}/.repo/local_manifests/
under ".repo"  folder i have: manifests, manifest.git, project-objects, projects, repo and manifest.xml

Regards,
Ryan

**Comment by jgeslin** [comment]
Hi,

If not already exists, you must create the local_manifests folder by yourself.

Regards,
Jeremy.
